export { default as BlogHeadBlock } from "./BlogHeadBlock"
export { default as ContactBlock } from "./ContactBlock"
export { default as FooterBlock } from "./FooterBlock"
export { default as HeaderBlock } from "./HeaderBlock"
export { default as ShareBlock } from "./ShareBlock"
export { default as TextBlock } from "./TextBlock"
